name: Deploy via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure remote dir exists
        env:
          TARGET_USER: ${{ secrets.TARGET_USER }}
          TARGET_HOST: ${{ secrets.TARGET_HOST }}
          TARGET_PATH: ${{ secrets.TARGET_PATH }}
        run: |
          ssh -o StrictHostKeyChecking=no ${TARGET_USER}@${TARGET_HOST} "mkdir -p ${TARGET_PATH}"
        shell: bash

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
        shell: bash

      - name: Install known_hosts or scan
        run: |
          mkdir -p ~/.ssh
          if [ -n "${{ secrets.KNOWN_HOSTS }}" ]; then
            echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          else
            ssh-keyscan -H "${{ secrets.TARGET_HOST }}" >> ~/.ssh/known_hosts
          fi
        shell: bash

      - name: Deploy with rsync
        env:
          TARGET_USER: ${{ secrets.TARGET_USER }}
          TARGET_HOST: ${{ secrets.TARGET_HOST }}
          TARGET_PATH: ${{ secrets.TARGET_PATH }}
        run: |
          rsync -avz --delete --exclude='.git' --exclude='.github' ./ ${TARGET_USER}@${TARGET_HOST}:${TARGET_PATH}
        shell: bash
